# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS' do
  use_frameworks!
  pod 'Fire', :path => '../'
end

target 'watchOS' do
  use_frameworks!
  pod 'Fire', :path => '../'
end

target 'macOS' do
  use_frameworks!
  pod 'Fire', :path => '../'
end

target 'tvOS' do
  use_frameworks!
  pod 'Fire', :path => '../'
end
