# Uncomment the next line to define a global platform for your project

target 'iOS' do
  platform :ios, '8.0'
  use_frameworks!
  pod 'Fire', :path => '../'
end

target 'watchOS' do
  platform :watchos, '2.0'
  use_frameworks!
  pod 'Fire', :path => '../'
end

target 'macOS' do
  platform :osx, '10.10'
  use_frameworks!
  pod 'Fire', :path => '../'
end

target 'tvOS' do
  platform :tvos, '9.0'
  use_frameworks!
  pod 'Fire', :path => '../'
end
